url: "https://themkat.net" 
baseurl: ""
title: "TheMKat's blog" 
paginate: 10
include: [".well-known"]
exclude: ["org", "*.sh", "*.org", "Gemfile", "Gemfile.lock"]
sass:
  style: compressed
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
  - jemoji
