url: "https://themkat.net" 
baseurl: ""
title: "TheMKat's blog" 
paginate: 10
include: [".well-known"]
exclude: ["org", "*.sh", "*.org"]
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-feed
