* [[https://themkat.net/][TheMkat.net]] - my personal blog
Welcome to the source code for my personal blog!


** Technologies used
One of my main goals from the beginning was to have a simple experience where I could blog directly from Org-Mode inside of Emacs. I found that the easiest way to do this was to use Jekyll, due to Github pages supporting it out of the box. The next step was simply to convert Org-Mode pages to HTML with headers Jekyll could understand :)


- [[https://jekyllrb.com/][Jekyll]]
  - HTML/SASS
  - Basic JavaScript
  - [[https://shopify.github.io/liquid/][Liquid Templating]]
- Emacs
  - [[https://orgmode.org/][Org-Mode]]
- Shell scripting
- Github Actions (to automate blogpost generation from Org-Mode to HTML files, create new tag pages automatically etc.)

** Dependencies for dev mode
For building and serving the site locally, the following is needed:
- Emacs
- Ruby
- [[https://github.com/emcrisostomo/fswatch][fswatch]]


Then simply run =./scripts/dev-mode.sh=


** Using the resources from this repo? License?
This is my own personal blog, so ALL texts/blog posts (i.e, content) are prohibited to be used by others (than me) without permission! That includes commercial AI models (e.g, OpenAI) where the model is NOT open source! I can allow open source models with permissive licenses, but only if you get my permission before using any of my content. The reason is that many crawlers (used by AI models) have been predatory in the way they just take data, and especially in problems they have caused with almost DDoSing domains... I know that mentioning it probably won't stop the problem, but at least I have made myself clear :joy:


That being said... there are tooling, like scripts and similar. Feel free to use scripts and snippets for your own projects :) If you use anything, please add a small comment in your HTML or code with a link to this repo. Remember that a lot of small blogs following their own path, meaning not using predatory SEO, have troubles being found. We are in this together, so let's help each other out :)
