#+OPTIONS: toc:nil num:nil
#+STARTUP: showall indent
#+STARTUP: hidestars
#+BEGIN_EXPORT html
---
layout: blogpost
title: Welcome to my blog!
tags: info
---
#+END_EXPORT

And so it begins! This is the first post of my new blog. I thought this first post could be about my goals, as well as the topics I intend to write about. Just so you know what to expect, given that you read this before I have managed write more...

* Goals
I had several goals when creating this blog, but the most important one was to have a place where I could write about the things that I find interesting. As you might have guessed, this is mostly related to computers. I LOVE computers! Not just programming, but the wonders that computers can do, and the achievement of the great individuals who have made it possible. 

I would summarize my goals as follows:
- Being able to blog from Org mode in Emacs (super important!)
- Having a place that could be in-part a diary about things I learn (and small projects), one part my private online journal for articles, and more. The gist of it is to do more writing, which I take a lot of pleasure in doing :) (beware that English is not my first language though...) 
- Having a simple design that will not get in the way of reading my articles. I'm intending to gradually improve it as I go, I know it is far from perfect! I dub this current design Terriblé.
- Maybe having a simple CI/CI pipeline to be able to play with Github Actions (secondary, but already in place :) ).


* What will I write about?
I plan to mostly write about computer related topics, with a dash of math and book recommendations on top (though mostly relating to computers or math...). Some other topics may also come up from time to time. 


* So...
What will the future show? Who knows. The only answer will be in the undiscovered country, the future!
