#+OPTIONS: toc:nil num:nil
#+STARTUP: showall indent
#+STARTUP: hidestars
#+BEGIN_EXPORT html
---
layout: blogpost
title: The essential Ayn Rand reading list
tags: books objectivism philosophy
---
#+END_EXPORT

You may have heard many negative things about Ayn Rand, or many positives, depending on where you have heard about her. She is a well known author and philosopher, whose points are often understood (both by people traditionally on the left, as well as so-called "conservatives"). There are many misconceptions as well out there, and doing your own research will help with that. Whether you will end up thinking Ayn Rand is the best philosopher or not, is not my goal here. What I want is for you to know about her works that you should read, what they are about, as well as having resources to understand her philosophy better. If not, I hope you may read some of her fiction books and enjoy the spectacle!



Before I begin, I have to admit I dreaded writing about this for a long time. Why? Not because I dislike her, I LOVE her works and I think her philosophy is one of the best ones there is (if not THE most rational). The reason for me being apprehensive is that she is controversial, and often get a lot of hate. From what I've seen online, a lot of this stems from misconceptions (a lot from the so called "conservatives"). Before we begin, let's get some facts on her set straight:
- She fled from the Soviet Union to the United States when she was younger.
- She had [[https://en.wikipedia.org/wiki/The_Passion_of_Ayn_Rand][an affair with Nathaniel Branden chronicled in the book The passion of Ayn Rand]] which conservatives like to pretend don't exist (at least those of them who seem to promote her). They are afraid of sexuality, and often use their "Christian morals" to condemn it. Ayn Rand on the other hand informed her husband of the affair before much happened, and rumor has it she had his blessing (though he was allegedly not a big fan of it). They were also married until his death, and she described him as the love of her life.
- She defended the individual as the basis for politics, not groups of people or the common good.
- She promoted free markets, laissez faire capitalism, which means separation of state and economics. Collectivist ideologies (socialism, communism, nazism, fascism etc.) that focus on a big state and the common good, never actually reach that goal. There is always someone to hate and blame (e.g, the Jews in Nazi Germany or the Bourgeois/rich in the Soviet Union), and restrictions that a lot of people will find overbearing. 
- She thought that the religious right (as we see today) tried to take us back to the middle-ages with their connection of church and state, forcing everyone to live by their mysticism. She disagreed with people who tried to force their religion on others, especially through the state.
- She defended abortions. [[https://www.youtube.com/watch?v=fRlvMJsehy8]["A man who claims to defend rights, and objects to the right to have abortions. Who wants to dictate to a woman in the most intimate, crucial, and tragical issue of their time, and wants to forbid it. That is no defender of rights, and no defender of capitalism!"]]. She thought Reagan and other so-called conservatives was equally to blame for destroying capitalism as the so-called liberals/leftists.
- She was not a fan of traditions or the focus on the nuclear family. Just because something is old does not make it good.
- She was not a fan of drugs, but believed we should be able to make our own choices to our bodies. (there is [[https://youtu.be/8KZUKJjgCqg?t=313][one history of her wanting to try marijuana]] after hearing about its positive effects from Nathaniel Branden though). 


Now that we have gotten that out of the way, let us continue. What are my criteria here. I've picked out 3 books I think is essential to get to know Ayn Rand's writings and her philosophy. Most of the books are fictional, but still have philosophical under-tones. I think this should be the beginning for exploring her works.


(like Ayn Rand, I will use the term man to mean human.)


*NOTE! I use Amazon Affiliate links in the headers below. This means I earn commissions from qualifying purchases.*


* 1. [[https://amzn.to/48syaV6][Atlas Shrugged]]
Who is John Galt? This is the essential question in all of the book. Often mentioned in times of despair, and for questions that people think it's meaningless to ask (because they are in a way impossible to answer). The book follows several characters in a near future where government creates more and more irrational rules and regulations, all posed as acts for the common good, but lobbied through by cronies (people who use government favors to gain special privileges). Dagny Taggart is our main heroine, and we see her fighting to keep her railroad company alive while all of the productive people around her slowly disappear. "What is wrong with the world?". Why ask useless questions? How deep is the ocean? How high is the sky? Who is John Galt? 


The misconceptions I see most online, is that the book only portrays CEOs disappearing and exaggerates their importance. That could not be farther from the truth! Sure, some CEOs disappear, but a lot are plain hardworking engineers, doctors, musicians, truck drivers etc. The CEOs are not of the MBA type either, they are hard working people who worked their way up from the bottom. Even Dagny who is born into a rich family works her way up the real way, in contrast to her (seemingly altruistic) brother who takes shortcuts. What the people who disappear have in common is that they have an extreme passion for what they do, that many computer engineers (at least those of us who started as kids or teens) can relate to. 


Atlas Shrugged is probably the best book I've ever read, and it inspired me to work harder for my own goals in life. It shows that a world we want "can be won, it exists" (in the words in one infamous character). Your mind belongs to you, and enslaving it in the name of public good is not the answer. (working voluntarily for the good of others on the other hand, can be a good thing)


If you disagree with the books message, that is completely fine! You have your own conviction and I have mine. Let's respect each other in a polite tone without the character attacks we often see today. Even if I'm one of those "wacky libertarians" (other peoples words), I understand that someone who is on the other side also works for a world that they perceive to be the best one.


* 2. [[https://amzn.to/4eZCrBU][The Fountainhead]]
Howard Roark is a young idealistic architect who has his own vision, but is forced to choose between it or adapting to what others think is great. At first glance, you may think he sounds like a lunatic, but that is not true. Indeed, he is a visionary. No one who has innovated has ever done what everybody else is already doing. This book deals with themes such as being true to your own ideals, reason, public perception and deception (through media), romantic love, and hate for people being different. We see Roark struggling through life as he unapologetically follow through on his own vision, trying to get the buildings he want to build into reality. He enjoys doing it immensely, and with great passion. From the book we have this exchange between him and the dean of the architect school he is expelled from:

#+BEGIN_VERSE
“Do you mean to tell me that you’re thinking seriously of building that way, when and if you are an architect?”

“Yes.”

“My dear fellow, who will let you?”

“That’s not the point. The point is, who will stop me?”
#+END_VERSE

This exchange highlights his passion for his craft. 


Roark is a man of great self esteem, and is what Ayn Rand perceives to be the ideal man. Her bullet point list is as follows:
- Rational
- A man of great self esteem
- Guided exclusively by reason
- Independent


Does that mean that this person is without feelings? No. A man of great passion for what he does, is also a wildly emotional (at least in my view). The point is to use your reason to guide you, not do purely emotional decisions. 



* 3. [[https://amzn.to/3Adtc1A][The Virtue of Selfishness]]
The two previous books on this list were works of fiction, but this one is different. This book contains a collection of essays on Objectivist ethics. Why do I like this book so much? This book provides answer to a lot of questions relating to morality (i.e, the concept of ethical selfishness), and the introduction of capitalism as the only moral system (and why).

This is NOT the book you should start with. I would first read the fiction books above, enjoy the spectacle and see if you are more curious to learn more about the philosophy. If you are, I would start with this book, then read [[https://amzn.to/3YgVi49][Capitalism: The Unknown Ideal]], and then go to the rest of her books based upon your interest in the subjects. Whether it is the books about [[https://amzn.to/3YBYSHq][writing fiction]], [[https://amzn.to/3NCYGkU][writing non fiction]], reading more about [[https://amzn.to/4eTd9VV][why we need philosophy]] (we as in everyone), her other fiction ([[https://amzn.to/40gQhuS][Anthem]] and [[https://amzn.to/48BQFGN][We The Living]]) or something else. 


* Final remarks
Ayn Rand is both an interesting character, as well as having written great works. If you want to learn more about her as a person (she is far from perfect, but no one is!), then I suggest reading the biography called [[https://amzn.to/3YCHoea][Goddess of the Market: Ayn Rand and the American Right]].


Would you have picked any other books as a starting point for someone new to Ayn Rand? Love the books? Hate them? Feel free to share in the comments below :) 
