#+OPTIONS: toc:nil num:nil
#+STARTUP: showall indent
#+STARTUP: hidestars
#+BEGIN_EXPORT html
---
layout: blogpost
title: More sci-fi books you should read!
tags: books
related_tags_count: 1
---
#+END_EXPORT

There is probably no secret that I love science fiction books and dream of the mysteries of space exploration. It's a nice way to fantasize about the future of technology, and to get your imagination going. Sometimes I get very inspired by these books, and it's also a great way to take a break from real life. 


[[https://themkat.net/2021/09/26/scifi_books_to_unwind.html][Love science fiction? Take a look at the list I made last year that contains several classic books.]]


*NB! Amazon affiliate links below in the images, titles and more. This means I earn commissions on qualifying purchases.*

#+BEGIN_EXPORT html
<br />
<br />
#+END_EXPORT


* [[https://amzn.to/3NBr3jx][Project Hail Mary by Andy Weir]]
Last month I finally  got around to reading this gem! [[https://amzn.to/3NBr3jx][Project Hail Mary]] follows astronaut Ryland Grace who wakes up in a spaceship without any memory of why he's there. It becomes clear that he is humanity's last hope for survival, and is far away from Earth. The mystery is unraveled by his memories coming to the surface. The book contains mystery, character development, friendship and more. It also has great twist and turns. This is a classic hard sci-fi story that gives a real sense of space exploration, and I was very pleasantly surprised by it. The mystery of what is happening is what makes it so great, so I don't think much should be spoiled here.


Something that gave me lots of joy was to see (at least in my view) programming being used to solve a problem realistically! Many books have very weird ways of portraying programming and solving problems with computers. In general the technology seems plausible'ish, even though some parts of it is far from what we have available at the moment (relax, this is made clear very early in the book). 


The audio book (audible) is the recommended way to enjoy it, as the narration by Ray Porter and the small sound effects take it to the next level

#+BEGIN_EXPORT html
<br />
<br />
#+END_EXPORT

* [[https://amzn.to/4hmssb9][Children of Time by Adrian Tchaikovsky]]
Children of Time follows two civilizations through thousands of years; humans traveling in their spaceship in cryo sleep, and a spider civilization evolving through that same time. The basic premise for this story is that a team of scientists wanting to colonize a planet of monkey servants planned to be released, evolving them through a nanovirus. This plan is sabotaged, and humanity seems end up at war that sets them back many years and destroys Earth. This leads to two things; a spaceship traveling to find a new suitable home, and the nanovirus being released without the monkeys being on the planet (evolving the spiders and other insectoid wildlife instead).


It's been a long time since I read this book, but the concept and world building has stuck by me. 


#+BEGIN_EXPORT html
<br />
<br />
#+END_EXPORT


* Darth Bane trilogy (Star Wars)
*NOTE! It should be noted that this book is in the Legends continuity, and is not a part of the main Star Wars canon. It was written before Disney bought the rights to Star Wars.*
 

Ever wondered how the rule of two came to be? This trilogy is the story of Darth Bane's life and how he came to be the Sith lord from Star Wars lore we all know. The first book starts with Dessel (future Bane) working in cortosis mines of Apatros. He dreams of his escape, but is indebted because of his father. We hear about the New Sith Wars in the background, and eventually Dessel is accepted into the Brotherhood of Darkness. From being a part of a group of many Sith, how does he end up forming the classic Rule of Two which we hear about in the Star Wars films?


During this story we again hear about places we have seen in other Star Wars literature and games, like Knight of the Old Republic. These include Valley of the Dark Lords, the Unknown World and more. We also hear about classic characters like Darth Revan. There should be enough fun fan service here, as well as a great engaging story to keep you interested! (given that you enjoy Star Wars off course). 


The trilogy consists of these books:
- [[https://amzn.to/40k32VO][Path of Destruction]]
- [[https://amzn.to/3YzEA1k][Rule of Two]]
- [[https://amzn.to/48lhYom][Dynasty of Evil]]


Another book that works perfectly as an audiobook! The sound effects, like lightsabers and spaceship sounds make it near perfect. It's always awkward sitting outside by yourself making lightsaber sounds while reading a book, so now you don't have to anymore :) (that was a joke...)
