#+OPTIONS: toc:nil num:nil ^:nil
#+STARTUP: showall indent
#+STARTUP: hidestars
#+BEGIN_EXPORT html
---
layout: blogpost
title: Best resources to learn Kotlin (in my view)
tags: programming kotlin books
---
#+END_EXPORT

Do you want to learn Kotlin? Wonder what resources you should use to learn it? In this article I collect a few different resources depending on your interests and skill level. You might pick a few, mix and match or do whatever you want that makes you learn the concepts. Only you know the way you learn things the best. Without further ado, let us dive into the resources!


*NOTE! When I recommend books, I use Amazon Affiliate links. This means I will earn commissions for qualified purchases.*


* Learning the basics
No matter your skill level, you will at some point refer to [[https://kotlinlang.org/docs/getting-started.html][the official language documentation]]. For many of you, this will probably be the best place to start as well. All the examples can be run directly on the website, but you want to try your own code snippets interactively you can do it on [[https://play.kotlinlang.org/][play.kotlinlang.org]]. If you already know Java, they have [[https://play.kotlinlang.org/koans/overview][an interactive track called Koans]] that teach you the basics of Kotlin. This program help you get familiar with the syntax and workings of the language.

There is probably two groups of people who end up reading this blog post; people new to programming in general, and people who know some programming and want to learn Kotlin. My recommendations are a bit different depending on which group you belong to. You may mix and match, but complete beginners will have a harder road with the resources aimed at people familiar with programming and/or the Java/JVM ecosystem.
- *Complete beginner*: If you are set on learning Kotlin as a beginner, I think I would start with the [[https://amzn.to/47jTYBa][Head First Kotlin book]]. It covers several programming concepts, and teaches you Kotlin from the ground up. It claims you should have some very basic scripting experience, but I think it is achievable with some effort (maybe supplement the official documentation above?). [[https://www.jetbrains.com/academy/][JetBrains Academy]] might be worth checking out, but I don't know too much about it. They describe their approach in [[https://www.youtube.com/watch?v=wBbYU7bcKHQ][this YouTube video]].
- *Familiar with programming and/or the Java/JVM ecosystem:* The absolute BEST book on Kotlin in my view is [[https://amzn.to/3KrT2Rv][Programming Kotlin by Venkat Subramaniam]]! It goes through the basics, as well as some examples using Spring and also creating Android applications. Several often ignored parts of the Kotlin syntax is covered, and even I learned something new when reading it a few years ago (I had programmed in Kotlin for almost a year by that point). It requires that you know the basics of programming, and also assumes that you know about the Java ecosystem, but it is manageable in my view. I know someone who have read it and only knew some C programming, and they were able to start programming Kotlin after reading at least parts of the book! One exercise those of you who are more experienced may find useful is to refactor one of your Java applications to Kotlin.


If you want to edit your files locally, you will also need an editor of some kind. Kotlin is created by JetBrains, the creators of IntelliJ IDEA. I would say that most people end up using [[https://www.jetbrains.com/idea/][IntelliJ IDEA]] for Kotlin, as they find it has the most complete tool support for the language. Other people, like myself, have a *very* strong preference for other editors like Emacs. On this blog you will find several articles about Kotlin in Emacs, [[https://themkat.net/2022/09/24/kotlin_in_emacs_redux.html][one recent]] and [[https://themkat.net/2021/11/03/kotlin_in_emacs.html][one older]]. The details mentioned in those articles can probably help you configure Kotlin IDE functionality in other editors, like Vim, as well.


* Next steps
So you know the basics now, and want to keep on learning new concepts. The play.kotlinlang.org site have [[https://play.kotlinlang.org/hands-on/overview][lots of hands-on labs you can try]], even though most of them probably are meant a bit for intermediates. If you want to learn a specific concept, like Native, Multiplatform, Spring Boot etc., then they might be worth a try. To stay up to date with Kotlin, Jetbrains has [[https://www.youtube.com/c/Kotlin][an excellent YouTube channel]] with talks, news about new features and more. There are several videos on their channel, ranging from basic concepts to more advanced topics:
- [[https://www.youtube.com/watch?v=n4WBip822A8&list=PLlFc5cFwUnmy6Fz9aq-JMlzk34ce5hJrg&index=5][Kotlin Standard Library safari]]: Tips on using the standard library and often overlooked parts of it.
- [[https://www.youtube.com/watch?v=i-kyPp1qFBA&list=PLlFc5cFwUnmyDrc-mwwAL9cYFkSHoHHz7][Evergreen Kotlin tips]] (usage of the Elvis operator, fully qualified names, nullability etc.)
- If you use Spring, or want to, then the [[https://www.youtube.com/watch?v=ihMhu3hvCCE&list=PLlFc5cFwUnmxOJL0GSSZ1Vot4KL2Vwe7x][Spring Time in Kotlin series]] is worth a watch. At least the videos containing what you are interested in. They cover reactive programming, coroutines and more.
- Some of you learn by seeing other people solve programming problems, like [[https://www.youtube.com/watch?v=abkHxIMJGIw][this interview problem]].



There are also some resources you can check out based upon other topics:
- *Android development*: Google announced first-class support for Kotlin in 2017, replacing Java. [[https://developer.android.com/kotlin][Development is covered extensively in its documentation]], including toolkits like Jetpack Compose that makes Android development more comfortable.
- *Compiling to native code (iOS, Linux, Windows, etc.):* Want to interface with C libraries? Or make native applications for phones like iPhone? Then [[https://kotlinlang.org/docs/native-overview.html][Kotlin Native]] is probably for you.
- *Multiplatform codebases*: This potentially combines the previous point with Android development, server side apps, frontend apps and more. [[https://kotlinlang.org/docs/native-overview.html][Multiplatform projects]] help you share code between several targets. This can help you make applications for Android and iOS, fullstack web apps and more! I'm not very familiar with this, but it seems interesting.
- *Kotlin for scripting*: Want to replace clunky big bash scripts with Kotlin code? Or maybe you just prefer automating with Kotlin instead of Python or NodeJS? [[https://github.com/kscripting/kscript][KScript]] makes this easy!
- *Domain specific languages in Kotlin*: I mentioned Venkat Subramaniam earlier, and he have written [[https://amzn.to/3OHl6CW][a book about domain specific languages in Kotlin]]. Might be worth checking out if you find the concept of domain specific languages useful. There is also [[https://themkat.net/2020/08/27/kotlin_dsl.html][an article on this blog]] about that topic.
- *Kotlin syntax and features you may have forgotten?* There is [[https://themkat.net/2022/01/16/kotlin_often_forgotten_features.html][an article on this blog]] for that!
  

Enjoy listening to podcasts? There is actually a podcast about Kotlin where they talk about libraries, approaches at companies etc. It's called [[https://talkingkotlin.com/][Talking Kotlin]], and is available where you usually listen to podcasts.


If you want to do software development professionally, I wrote [[https://themkat.net/2020/09/07/career_boosting_books.html][an article with book recommendations for that]] a few years ago. It has a slight focus on the Java ecosystem, but many of the books are useful either way.
