#+OPTIONS: toc:nil num:nil ^:nil
#+STARTUP: showall indent
#+STARTUP: hidestars
#+BEGIN_EXPORT html
---
layout: blogpost
title: Essential books on the Rust programming language
tags: programming rust books
---
#+END_EXPORT


Rust is gaining popularity fast, and is a language loved by many (including myself). It has recently been used for device drivers in the Linux kernel. While many early adopters did more low level code, it is gaining popularity in higher level problems as well (e.g, writing REST APIs and CRUDL database applications). You might want to learn Rust, and wonder about some resources to use. That is exactly what we will look into in this article! While books are the main topics, links to other useful resources are also provided.



You might also want to check out my other posts on Rust, like [[https://themkat.net/2022/10/31/what_i_love_about_rust.html][this list of what I love about it]]!



*As an Amazon Affiliate I make commissions on qualifying purchases. The links to the books below are affiliate links (images and titles).*


#+BEGIN_EXPORT html
<br />
<br />
#+END_EXPORT



* [[https://amzn.to/3rVvON7][The Rust Programming Language]] by Steve Klabnik and Carol Nichols
#+BEGIN_EXPORT html
<a href="https://www.amazon.com/Rust-Programming-Language-2nd-ebook/dp/B0B7QTX8LL?_encoding=UTF8&qid=1691245088&sr=1-1&linkCode=li3&tag=themkat0f-20&linkId=b90fa561be0a5fa5fa0394a9b8e2a56d&language=en_US&ref_=as_li_ss_il" target="_blank"><img border="0" class="blogfloatleftimg" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B0B7QTX8LL&Format=_SL250_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=themkat0f-20&language=en_US" ></a><img src="https://ir-na.amazon-adsystem.com/e/ir?t=themkat0f-20&language=en_US&l=li3&o=1&a=B0B7QTX8LL" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
#+END_EXPORT


*What is it about?* This book teaches you the complete basics of the language, its syntax and how to solve various problems. Concepts include the build tools, the ownership model, pattern matching and more.


*Additional resources:*
- [[https://doc.rust-lang.org/beta/book/index.html][The book itself, available online officially]] (for free in HTML). Yes, the book is available for free. It might change at times, and differ slightly from the physical (and Kindle) book releases. If you don't have a lot of money at the moment, it is good to have it for free (legally!).  
- [[https://github.com/rust-lang/rustlings][rustlings]]. Interactive exercises on the basics of Rust. Works great as a supplement to the book!
- [[https://doc.rust-lang.org/beta/reference/index.html][Rust documentation]]. For when you are unsure on concepts. (not necessarily good as a standalone resource)
- [[https://www.youtube.com/@letsgetrusty][Let's get Rusty]]. Videos with walkthroughs on basic concepts, changes from version to version, libraries and more! People new to Rust will probably want to watch [[https://www.youtube.com/watch?v=iU21KZ4i6bU][A Tour of Rust]].


*Who should read it?* People who want to learn the Rust programming language, but who have written in another language before. If you are clever, you will probably be able to pick it up without knowing other programming languages as well.


#+BEGIN_EXPORT html
<br />
<br />
#+END_EXPORT


* [[https://amzn.to/3OHmntI][Rust Brain Teasers]] by Herbert Wolverson
#+BEGIN_EXPORT html
<a href="https://www.amazon.com/Rust-Brain-Teasers-Herbert-Wolverson-ebook/dp/B09Z5T2CDP?keywords=rust+brain+teasers&qid=1691245171&s=digital-text&sprefix=rust+brain+teas%2Cdigital-text%2C158&sr=1-1&linkCode=li3&tag=themkat0f-20&linkId=524a80859f78f864063208895de95627&language=en_US&ref_=as_li_ss_il" target="_blank"><img border="0" class="blogfloatleftimg" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B09Z5T2CDP&Format=_SL250_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=themkat0f-20&language=en_US" ></a><img src="https://ir-na.amazon-adsystem.com/e/ir?t=themkat0f-20&language=en_US&l=li3&o=1&a=B09Z5T2CDP" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
#+END_EXPORT


*What is it about?* Various small problems that might have unexpected results. If you have read something like [[https://amzn.to/3s3681m][Java Puzzlers]] there are certain similarities. While the title makes the book seem advanced, it is really not. That is also the main complaints people have with the book. If you are not super experienced with Rust, and fairly new to it, you will probably learn a thing or two. Some of the problems might be obvious, and if not you will hopefully learn something new.

*Additional resources:* See the suggested resources for the previous and next entries :)


*Who should read it?* People who have read the previous book (or learned the basics in another way), and want to look into code examples that might at first seem peculiar. If you are a group of people learning Rust, this book might be fun to read together. You can look at the issues, and guess together what will happen. 


#+BEGIN_EXPORT html
<br />
<br />
#+END_EXPORT


* [[https://amzn.to/3QmUF6N][Rust for Rustaceans]] by Jon Gjengset
#+BEGIN_EXPORT html
<a href="https://www.amazon.com/Rust-Rustaceans-Programming-Experienced-Developers-ebook/dp/B0957SWKBS?keywords=rust+for+rustaceans&qid=1691245284&s=digital-text&sprefix=rust+for+ru%2Cdigital-text%2C161&sr=1-1&linkCode=li3&tag=themkat0f-20&linkId=220cffff286c72daf088d653c0f9f5cb&language=en_US&ref_=as_li_ss_il" target="_blank"><img border="0" class="blogfloatleftimg" src="//ws-na.amazon-adsystem.com/widgets/q?_encoding=UTF8&ASIN=B0957SWKBS&Format=_SL250_&ID=AsinImage&MarketPlace=US&ServiceVersion=20070822&WS=1&tag=themkat0f-20&language=en_US" ></a><img src="https://ir-na.amazon-adsystem.com/e/ir?t=themkat0f-20&language=en_US&l=li3&o=1&a=B0957SWKBS" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
#+END_EXPORT

*What is it about?* Now that you know the basics of Rust, it is time to go deeper! Yes, exactly that. This is a book for intermediates who want to learn more advanced concepts needed to be a more professional Rust developer. Some topics covered include:
- Writing good idiomatic Rust code
- Ideas on how the compiled code will look and behave, considerations to be made etc. Useful to understand that the compiler is in fact a compiler, and not magic...
- Different perspectives to understand the ownership model. (also relating to the previous point).
- Concurrency (async/await) and parallelism.
- Macros, both declarative and procedural. This was one of the selling points for me, as I had been missing macros a lot from my time coding various Lisps.
- Unsafe Rust and Foreign Function Interface (interfacing with non-Rust libraries)



*Additional resources:*
- [[https://www.youtube.com/@jonhoo][The authors YouTube channel]]. Contains deep dives into  many different concepts in Rust. If you like to watch videos, his [[https://www.youtube.com/watch?v=rAl-9HwD858&list=PLqbS7AVVErFiWDOAVrPt7aYmnuuOLYvOa][Crust of Rust series]] goes into some of the concepts from the book (e.g, unsafe Rust, macros, and concurrency). There are also various walkthroughs of projects, videos on implementing specific concepts, and just more casual Q&As. 
- [[https://www.youtube.com/@letsgetrusty][Let's get Rusty]]. I know I mentioned this one above as well, but it provides good videos on Rust for both beginners and intermediates. For people who are more well versed in the language, there are videos on specific libraries and more advanced concepts. There are also videos that goes through the new features in new versions of Rust.
- [[https://www.youtube.com/@LowLevelLearning][Low Level Learning]]. YouTube channel about mostly low level coding and embedded devices. It has a lot of nice videos on embedded Rust, and good practices for writing better and more idiomatic Rust code.
  


*Who should read it?* People who want go deeper into the concepts of the language, and also understand how everything works. There can be many reasons you may want to read this book, some of them include:
- You are an API developer who want to know better how to write your APIs and related code.
- You write embedded code and need an understanding of unsafe Rust.
- You want write a Foreign Function Interface for a C/C++ (or similar) library in Rust, and therefore need to understand unsafe Rust. You might also want to write a crate wrapping the unsafe code into "safe" operations and need more details on how that should be done.
- You want to understand how concurrency and parallel programming work in Rust. Not just the complete basics, but how the scheduling etc. might work.
- You want to work with Rust as a professional, and therefore want deeper understanding to make yourself more attractive in the job market.

Probably more as well, but if you feel close to any of these points, then I would recommend reading the book (and/or looking into the resources specified above).
