#+OPTIONS: toc:nil num:nil
#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: ^:{}
#+BEGIN_EXPORT html
---
layout: blogpost
title: "One of the projects I regret doing: AITales"
tags: ramblings
related_tags_count: 1
---
#+END_EXPORT

A few short years ago, ChatGPT entered the mainstream. Suddenly the hype was everywhere. The experience was less polished, and the output was not what you would usually expect. Still, it got extremely popular. For some reason, I ended up looking a bit into the chatbot APIs that was offered. This is that story.


A quick note on wording before we begin. AI is obviously an acronym for artificial intelligence. I use the terms genAI (generative AI) to describe these large language models (LLMs) that are used to generate text or images. For the other kinds of AI, like the machine learning models for heart rhythm etc., I often use the term assistive AI. These are often smaller purpose built models for a specific task, and often don't require big data centers. Most of us don't really have that much of an issue with these kinds of AI models. They are also not the topic of this article. 



Like many science fiction nerds, I was really fascinated with the various depictions of artificial intelligence. You have interesting characters like the Red Queen in Resident Evil, Brainiac in Superman comics, HAL-9000 in 2001 A Space Odyssey, Data in Star Trek: The Next Generation, and so many more. Creating artificial beings seemed like such a cool idea at the time. It was fun discussing the ethics of it all in nerdy circles. What does it truly mean to be human? Star Trek: The Next Generation covers this exact topic in the episode "The Measure of a Man" (season 2, episode 9). Should Data be considered sentient or not? (the episode is still worth a watch! Some people like to discuss it as an allegory for other topics as well, like slavery). This techno optimism fueled many researchers. For a while, everything was so [[https://en.wikipedia.org/wiki/Uncanny_valley][uncanny valley]] that it was interesting in a way. One of my favorites from the pre-ChatGPT era was [[https://www.youtube.com/watch?v=4MKAf6YX_7M][this Eurovision inspired song]] made by an early neural network. You can find many other such works if you do a techno-archeological deep dive. The common factor is this weird mix of kitsch, humor and the infamous uncanny valley. Suddenly in the beginning of 2023, the ChatGPT hype reached the mainstream. Fueled by hype and the fascination described earlier, I embarked on a stupid project...



Early in February 2023, I was walking around Oslo. I wanted some new electronic components for my various microcontroller experiments. I ended up buying those, and they were fun. The most positive part of that day was, without a doubt, the amazing döner kebab I had for lunch. I can probably not blame the kebab for what happened in my head next, but I do wish that it would have given my diarrhea instead. At least then I would have been stuck on the loo... I got the "amazing" idea to use the ChatGPT APIs to generate stories. OpenAI had probably trained their models on all the public domain books and texts they could find, right? (We all know that they did NOT in any way just legally use public domain works). That would give some truly wacky uncanny valley stories, right? So I got home, and started coding it. A simple Rust command line tool was made to use the ChatGPT REST APIs, and a Github Action was used to run this tool periodically. A nice website was added to present the stories. All coded by hand, and the only genAI generated data was the responses from the ChatGPT APIs. The project was [[https://github.com/themkat/aitales][AITales]], which can still be found on my Github account. At first, it was interesting. After seeing more and more stories, I felt so jaded. The uncanny valley aspect was fun for a while, but it quickly became apparent how much soulless garbage that was coming out of it. Some stories could almost pass as something a lower secondary school student might write. Beyond the "science experiment" part of seeing a few stories, the project was quickly getting boring. Like other people, I got the feeling that we might see generated text like these stories flood the internet in a few years. After about a year, I archived the project. (What took so much time? I was not in a good mental state either at the time due to medical shit, which you can read more about that in other blog posts.).



Seeing how this was not just a tool, but an instrument to replace human work, was what really made me despise genAI. Suddenly, the questions on replacing all sorts of professions and creative outlets got discussed way more in all sorts of media outlets. Let's not forget flooding the internet with slop and drowning out creative works... Other people might have seen it a mile away, but I was too caught up in the optimistic science fiction bubble to notice. It only got worse from there. A blog post where I discuss topics like these, is usually a place I would have liked to have lists. Now, both unordered lists and em-dashes are seen as a way of identifying generated contents from places like ChatGPT. You know what? Fuck it, here is a list anyway:
- The data is NOT trained on just public domain data! They have not gotten consent to use all of their training data in this way. The big companies like Anthropic and OpenAI have used tons of data they have not gotten permission to use, and they try to make this seem like fair use. Some of their supporters try to explain this as the language models "learning" data like a human would, but I find that far fetched. A statistical copying machine is a whole other beast, and a human is in most cases not able to copy things to memory the same way. For an artist, tracing or drawing from reference would in no way produce an exact copy. Same with a coder learning from reading code. (unless they just copy paste off course). If these language models have patterns for an exact use case they are trained on, they might give the exact thing back. You can read [[https://blog.terrygodier.com/2026/08/09/mea-culpa-dark-hours.html][one such story about a web application on Terry Godiers blog]]. The lack of consent is a big issue for me here! Consent is important in all situations in our lives. "You should not have put your work online" seems to me like a version of "she asked for it because of what she was wearing". Putting something online has ALWAYS come with a license. You can not use any image you find online for anything you want, and any one that is tech literate will know that they should check the license. That is why anyone making content online looked for stock images or images with creative commons licenses when they needed an image for their website/blog/video. Using an image from a news outlet like CNN comes with strict copyright or rules on allowed usage. Same with software licensing. One example is the GPL licenses, where you had to release your source code if you made a derivative work.
- The environmental impact is huge. So many new data centers are being built, and that is not without consequences. These issues range from electricity usage and pollution, to water consumption. [[https://news.mit.edu/2025/explained-generative-ai-environmental-impact-0117][MIT News]] and [[https://www.nature.com/articles/d41586-024-00478-x][Nature]] has summaries. Do we really need to worsen climate change, and make energy rationing a reality, just because people want a fast and easy way to generate slop?
- [[https://en.wikipedia.org/wiki/Project_Panama][Anthropic's Project Panama]] seem dystopian and scary. They are buying old and rare books to train their models, but they are destroying the books in the process. It is not far fetched to believe that they want you to only find the information through them. I could probably continue down a tangent of what-ifs with authoritarian governments, the extreme data mining, possibility of constant surveillance and more, but you probably get the gist.




AITales still fills be with regret. There are a few reasons why I do not delete the project from Github:
- *Owning your shameful moments:* If I would hide it, and someone found out about it, they would wield power over me if it truly bothered me that much. Having it in public is a step in showing that I make mistakes and that no one is perfect. We all have things we are ashamed of. My shameful moment is a time capsule into a more technologically optimistic version of myself. One where all of this nonsense was just a stupid science experiment. The crappy stories reflect that.
- *Code examples:* Most of the Github Actions code might actually be an ok reference for people interested in Github Actions or the Rust libraries I have used. The code was still 100 % handcoded. Only the response from the ChatGPT APIs ever contained anything genAI generated. 



Fuck OpenAI and fuck Anthropic. These companies ruin our planet and our resources, and they want to own our intellectual capacity.  If you REALLY want a LLM for some stupid reason, run one locally. Then you will not support the big companies ruining our planet.
