name: Jekyll site CI. Publishes org mode to html, create tag pages, push, and build jekyll.

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setupsite:
    # [SKIP] Tag to skip Emacs org mode to html and tag generation
    if: "!contains(github.event.head_commit.message, '[SKIP]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: purcell/setup-emacs@v4.0
        with:
          version: 28.1
      - name: Run Emacs Org mode publish to convert Org mode files to HTML
        run: ./emacs_headless_publish.sh
      - name: Setup new tags if any
        run: ./create_tag_pages.sh
      # only publish the pages for master/main branch activity
      - name: Publish new files if any
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com" && \
          git config --local user.name "GitHub Action" && \
          git add . && \
          git commit -am "[SKIP] New org mode articles and/or tags" && \
          git push
