name: Jekyll site CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  setupsite:
    # [SKIP] Tag to skip Emacs org mode to html and tag generation
    if: "!contains(github.event.head_commit.message, '[SKIP]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@v6.0
        with:
          version: 28.1
      - name: Run Emacs Org mode publish to convert Org mode files to HTML
        run: ./emacs_headless_publish.sh
      - name: Setup new tags if any
        run: ./create_tag_pages.sh
      # only publish the pages for master/main branch activity
      - name: Publish new files if any
        if: github.event_name != 'pull_request'
        run: |
          git config --local user.email "action@github.com" && \
          git config --local user.name "GitHub Action" && \
          git add . && \
          git commit -am "[SKIP] New org mode articles and/or tags" && \
          git push
  build:
    runs-on: ubuntu-latest
    needs: setupsite
    if: "always()"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.190.0
        with:
          ruby-version: '3.1'
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: Upload artifact
        if: github.event_name != 'pull_request'
        uses: actions/upload-pages-artifact@v3
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: "always() && 'success' == needs.build.result && github.event_name != 'pull_request'"
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
